### ISSUE TITLE
Quick Log

### ISSUE THREAD

**Issue by prostolyubo** [redpangilinan/iotawise#10]
Suggestion: Add a "Quick Log" button next to an activity dropdown on a dashboard. It should immediatelly create a log with single count on today's date. Users will mostly log a simple entry, choosing an "Add Log" from a dropdown, then filling a form, and confirming it just makes a simple task very tedious.

PS: Great simple app, just what I was looking for, thank you!
I would gladly contribute, I'll just need to learn some typescript first.

**Comment by redpangilinan** [comment]
Thanks for the suggestion! Makes sense since users can access the dropdown by going to the activity page anyways. I'll implement it once I get the time for this project, probably in a few days.

**Comment by prostolyubo** [comment]
> Thanks for the suggestion! Makes sense since users can access the dropdown by going to the activity page anyways. I'll implement it once I get the time for this project, probably in a few days.

Not necessarily get rid of the dropdown. Let's just add it besides:
<img width="691" alt="image" src="https://github.com/redpangilinan/iotawise/assets/45892416/a4760edf-1f1b-4c74-82de-189598160deb">
