### ISSUE TITLE
[BUG] UI Small bug's

### ISSUE THREAD

**Issue by websharkdev** [redpangilinan/iotawise#13]
![image](https://github.com/redpangilinan/iotawise/assets/47607282/c28d8d47-f76f-4aca-b05f-ab66a60d5731)
![image](https://github.com/redpangilinan/iotawise/assets/47607282/ebc3bb4c-cee8-466a-b449-c7bfe7b57cbc)
![image](https://github.com/redpangilinan/iotawise/assets/47607282/6ec1234c-f2db-429e-a228-df5b893710d7)

These are minor bugs, but in my opinion, they are noise that devalues ​​this cool project.

UPD: Remove the description as required to create an activity

**Comment by websharkdev** [comment]
Guys, this shit is awesome, thank you so much for this project. I've been looking for a nice habit tracker for a loooooong time.

**Comment by redpangilinan** [comment]
Glad you appreciate the project! I'll fix this once I get the time since I'm currently busy with work.

**Comment by redpangilinan** [comment]
UI issues has been fixed

Check these commits for more info: c17df7b 9422977
